logging:
  level:
    shopcompare.*: debug
    .*: info
  file: shopCompare.log

server:
  tomcat:
    accesslog:
      enabled: true

proxy:
  should-use: false
  port: 8888

superget:
  api-url: https://api.superget.co.il/
direct:
  stores:
    - 241
    - 889
    - 298
    - 982
    - 986
    - 788
    - 266
    - 480
    - 910
    - 878
    - 201
    - 887
    - 282
    - 884
    - 758
  products:
    - 1987
    - 1974
    - 8356
    - 748
    - 9619
    - 745
    - 20172
    - 786
    - 20173
    - 779
    - 789
    - 769
    - 90431
    - 747
    - 8491
    - 12706
    - 1996
    - 1963
    - 1958
    - 1965
    - 9447
    - 1952
    - 784
    - 7899
    - 750
    - 771
    - 772
    - 768
    - 758
    - 759
    - 776
    - 763